In [2]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
a.shape


(3,)

In [4]:
[[1,2,3],
 [4,5,6]]

[[1, 2, 3], [4, 5, 6]]

In [5]:
b=np.array([[1,2,3],
            [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
b.shape


(2, 3)

In [7]:
b.reshape((6,))

array([1, 2, 3, 4, 5, 6])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [11]:
np.linspace(1,12,num=11)

array([ 1. ,  2.1,  3.2,  4.3,  5.4,  6.5,  7.6,  8.7,  9.8, 10.9, 12. ])

In [12]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
b[0]

array([1, 2, 3])

In [14]:
b[0][0]

np.int64(1)

In [15]:
b[1]

array([4, 5, 6])

In [16]:
b[0, 0]

np.int64(1)

In [17]:
b*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [18]:
for i in range(2):
    for j in range(3):
        b[i,j]*=2
b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [19]:
b>9

array([[False, False, False],
       [False,  True,  True]])

In [20]:
b[b>7]

array([ 8, 10, 12])

In [21]:
np.mean(b,axis=0)

array([5., 7., 9.])

In [22]:
np.std(b,axis=-1)

array([1.63299316, 1.63299316])

In [23]:
np.concatenate([b,b*2])

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [ 4,  8, 12],
       [16, 20, 24]])

In [24]:
np.concatenate([b,b*2],axis=1)

array([[ 2,  4,  6,  4,  8, 12],
       [ 8, 10, 12, 16, 20, 24]])

In [25]:
from tensorflow.keras.datasets import mnist
(X_train, y_train),(X_test,y_test)=mnist.load_data()

In [26]:

X_test.shape

(10000, 28, 28)

In [109]:
#ARRAY A
#SAVE A INTO A FILE
#LOAD A BACK INTO MEMORY FROM THE FILE