In [6]:
import numpy as np 
from scipy.signal import convolve
input_feature_map = np.array([
    [1, 2, 3, 4, 5, 6, 7], 
    [2, 3, 4, 7, 6, 6, 6],
    [3, 4, 5, 8, 5, 4, 2], 
    [4, 5, 6, 8, 6, 5, 2],
    [5, 6, 7, 8, 7, 4, 4],
    [6, 7, 8, 3, 8, 2, 5],
    [7, 8, 9, 2, 9, 3, 4]
])
kernel = np.array([
    [1, 0, 0],
    [0, 1, 0], 
    [0, 0, 1]
])
Stride = 1
Rate = 2


In [7]:
kernel_conv=np.zeros((kernel.shape[0]+Rate, kernel.shape[1]+Rate))
kernel_conv

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
for i in range (kernel_conv.shape[0]):
    if (i%2!=0):
        continue
    else:
        for j in range (kernel_conv.shape[0]):
            if (j%2!=0):
                continue
            else:
                kernel_conv[i,j]=kernel[i//2,j//2]
kernel_conv

array([[1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
output_feature_map = convolve(input_feature_map, kernel_conv, mode='valid')
output_feature_map

array([[13., 14., 12.],
       [16., 13., 15.],
       [19., 15., 16.]])